version: '3'

services:
  nginx:
    image: nginx
    container_name: "game-match-back-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./:/src
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      ./infra/php
    container_name: "game-match-back-php"
    volumes:
      - ./:/src
  mysql:
    image: mysql:5.7
    container_name: "game-match-back-mysql"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=game_match_back
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root
    ports:
      - 13307:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis
    container_name: "game-match-back-redis"
    ports:
        - "16379:6379"